"""initial schema

Revision ID: 153b8202e128
Revises: 
Create Date: 2026-04-07 20:59:05.039838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '153b8202e128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('os_family', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('kernel_version', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_criticality', 'assets', ['criticality'], unique=False)
    op.create_index('idx_assets_ip', 'assets', ['ip_address'], unique=False)
    op.create_table('cve_enrichment',
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_v3_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cvss_v3_vector', sa.String(length=100), nullable=True),
    sa.Column('epss_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('epss_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('epss_updated_at', sa.Date(), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('scanner_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_report_path', sa.String(length=500), nullable=True),
    sa.Column('vuln_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('epss_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('epss_percentile', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('ssvc_decision', sa.String(length=20), nullable=True),
    sa.Column('scope_category', sa.String(length=30), nullable=True),
    sa.Column('affected_package', sa.String(length=200), nullable=True),
    sa.Column('affected_version', sa.String(length=100), nullable=True),
    sa.Column('fixed_version', sa.String(length=100), nullable=True),
    sa.Column('affected_file', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vulns_asset', 'vulnerabilities', ['asset_id'], unique=False)
    op.create_index('idx_vulns_cve', 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index('idx_vulns_kev', 'vulnerabilities', ['is_kev'], unique=False, postgresql_where=sa.text('is_kev = TRUE'))
    op.create_index('idx_vulns_priority', 'vulnerabilities', [sa.literal_column('priority_score DESC')], unique=False)
    op.create_index('idx_vulns_scope', 'vulnerabilities', ['scope_category'], unique=False)
    op.create_index('idx_vulns_status', 'vulnerabilities', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('remediation_id', sa.UUID(), nullable=True),
    sa.Column('vulnerability_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('action_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_chain', sa.Text(), nullable=True),
    sa.Column('pre_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('post_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_event', 'audit_log', ['event_type'], unique=False)
    op.create_index('idx_audit_remediation', 'audit_log', ['remediation_id'], unique=False)
    op.create_index('idx_audit_time', 'audit_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_time', table_name='audit_log')
    op.drop_index('idx_audit_remediation', table_name='audit_log')
    op.drop_index('idx_audit_event', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_vulns_status', table_name='vulnerabilities')
    op.drop_index('idx_vulns_scope', table_name='vulnerabilities')
    op.drop_index('idx_vulns_priority', table_name='vulnerabilities')
    op.drop_index('idx_vulns_kev', table_name='vulnerabilities', postgresql_where=sa.text('is_kev = TRUE'))
    op.drop_index('idx_vulns_cve', table_name='vulnerabilities')
    op.drop_index('idx_vulns_asset', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_table('scans')
    op.drop_table('cve_enrichment')
    op.drop_index('idx_assets_ip', table_name='assets')
    op.drop_index('idx_assets_criticality', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
