"""add scan_reports table and report_id FKs

Revision ID: 3a96258d090b
Revises: e106a8a6cb64
Create Date: 2026-04-09 17:42:07.066251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a96258d090b'
down_revision: Union[str, Sequence[str], None] = 'e106a8a6cb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scanner_types', sa.String(length=200), nullable=False),
    sa.Column('total_vulns', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_asset', 'scan_reports', ['asset_id'], unique=False)
    op.create_index('idx_report_status', 'scan_reports', ['status'], unique=False)
    op.add_column('scans', sa.Column('report_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'scans', 'scan_reports', ['report_id'], ['id'])
    op.add_column('vulnerabilities', sa.Column('report_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_vuln_asset_cve'), 'vulnerabilities', type_='unique')
    op.create_index('idx_vulns_report', 'vulnerabilities', ['report_id'], unique=False)
    op.create_unique_constraint('uq_vuln_report_asset_cve', 'vulnerabilities', ['report_id', 'asset_id', 'cve_id'])
    op.create_foreign_key(None, 'vulnerabilities', 'scan_reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerabilities', type_='foreignkey')
    op.drop_constraint('uq_vuln_report_asset_cve', 'vulnerabilities', type_='unique')
    op.drop_index('idx_vulns_report', table_name='vulnerabilities')
    op.create_unique_constraint(op.f('uq_vuln_asset_cve'), 'vulnerabilities', ['asset_id', 'cve_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vulnerabilities', 'report_id')
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_column('scans', 'report_id')
    op.drop_index('idx_report_status', table_name='scan_reports')
    op.drop_index('idx_report_asset', table_name='scan_reports')
    op.drop_table('scan_reports')
    # ### end Alembic commands ###
