"""add scanner_task_id, config to scans; ssh_port, scan_config to assets

Revision ID: 547acffb1125
Revises: 153b8202e128
Create Date: 2026-04-07 21:52:22.894294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '547acffb1125'
down_revision: Union[str, Sequence[str], None] = '153b8202e128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('ssh_port', sa.Integer(), nullable=False, server_default='22'))
    op.add_column('assets', sa.Column('scan_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('scans', sa.Column('scanner_task_id', sa.String(length=200), nullable=True))
    op.add_column('scans', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'config')
    op.drop_column('scans', 'scanner_task_id')
    op.drop_column('assets', 'scan_config')
    op.drop_column('assets', 'ssh_port')
    # ### end Alembic commands ###
