"""add unique constraint on asset_id cve_id

Revision ID: e106a8a6cb64
Revises: 8584fe512a40
Create Date: 2026-04-09 17:32:35.183792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e106a8a6cb64'
down_revision: Union[str, Sequence[str], None] = '8584fe512a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vuln_asset_cve', 'vulnerabilities', ['asset_id', 'cve_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vuln_asset_cve', 'vulnerabilities', type_='unique')
    # ### end Alembic commands ###
